image: python:3.12

stages:
    - setup
    - test
    - deploy

before_script:
    - python --version; pip --version
    - pip install virtualenv
    - python -m virtualenv virt
    - dir
    - virt\Scripts\activate
    - pip install -r requirements.txt

setup:
    stage: setup
    script:
        - pip install -r requirements.txt

run_tests:
    stage: test
    script:
        - echo "Virtual environment activated"
        - pytest test

deploy:
    stage: deploy
    script: 
        - python src/ui/Main.py